Feature/read metrics of file
fga-eps-mds/2021-2-MeasureSoftGram-Service pull request #14
Opened 2022-04-05 22:50 UTC by Marcos574

# Adicionando a lógica para salvar as métricas dos arquivos no banco de dados

## Descrição
Verifica se o ID informado pelo usuário da pré configuração existe e salva as métricas do arquivo fornecido no banco de dados

[Ler as métricas do arquivo](https://github.com/fga-eps-mds/2021-2-MeasureSoftGram-Doc/issues/56)

## Porque este Pull Request é necessário?
Para que o MeasureSoftGram seja capaz de salvar as métricas do arquivo json fornecido pelo usuário no banco de dados

## Critérios de aceitação
- [ ] Somente arquivos .json são válidos
- [ ] Poder selecionar no sistema de arquivos o arquivo desejado
- [ ] O sistema deve informar erro se o arquivo não existir ou não puder ser aberto
- [ ] O sistema deve informar se o JSON lido não é no formato sonar
- [ ] O sistema deve validar as métricas recebidas com as métricas esperadas para a pré configuração do modelo e informar erro caso se preciso
- [ ] O sistema deve validar se as métricas estão em formato numérico (NaN), não nulo e informado erro
- [ ] O arquivo json deve ter uma chave de baseComponent
- [ ] Receber um ID de pré-configuração válido
- [ ] Exibir mensagem de aviso no caso de sucesso ou de erro

## Tarefas

- [x] Criar o comando para receber o arquivo
- [x] Receber o caminho para o arquivo
- [x] Receber o ID da meta para associação
- [x] Abrir o arquivo
- [x] Informar se o arquivo não for compatível
- [x] Criar abstração modelo das métricas (MVC)
- [x] Criar endpoint para salvar as métricas
- [x] Validar os dados recebidos em relação ao modelo
- [x] Enviar as métricas do cliente para o servidor
- [x] Informar para o usuário o status da requisição

Closes #56

2022-04-06 14:30 UTC, igor-paiva commented on src/resources/metrics.py
> +            print("Id founded!")
Se uma request for mandada passando um id de pré configuração inválido o que vai acontecer?

Lembrem-se que a requisição vem de algum lugar pela rede e o protocolo que é usado para essa conversa é o HTPP. Usar print dizendo que encontrou e não encontrou não chega na pessoa que fez a request (não vai na resposta da requisição). As requisições e respostas já são gravadas nos logs da aplicação tbm, então esse print aqui é desnecessário.

2022-04-06 14:31 UTC, igor-paiva commented on src/resources/metrics.py
> +        return pre_config_metrics.to_json(), 201
Deveria retornar sempre 201?

2022-04-08 04:13 UTC, igor-paiva requested changes

2022-04-08 04:13 UTC, igor-paiva commented on src/resources/metrics.py
> +            pre_config_metrics.metrics_list = data
Tem uma sintaxe mais simples:

```py
Metrics(metrics_list=data)

# E ainda dá pra encadear o save
Metrics(metrics_list=data).save()
```

2022-04-08 04:13 UTC, igor-paiva commented on src/resources/metrics.py
> +            return pre_config_metrics.to_json(), 201
A CLI precisa dos dados das métricas que foram salvas? Pelo que vi não, mas pergunto pois se não precisa não tem necessidade de mandar esses dados na resposta da requisição (lembrem-se que quanto mais coisa para transferir, maior é o tempo para enviar via rede)

2022-04-08 04:13 UTC, igor-paiva commented on tests/integration/test_metrics.py
> +    response = client.post("/pre-config-metrics", data=dict)
Na nossa API vamos sempre se comunicar via JSON. Podem mudar esse `data` para `json`. Aí vocês vão ver que todos os testes (daqui pra baixo) vão falhar.

2022-04-08 04:13 UTC, igor-paiva commented on tests/integration/test_metrics.py
> +    }
Vocês utilizam praticamente o mesmo dict, só muda o id. Nesses casos: [DRY (Don't repeat yourself)](https://pt.wikipedia.org/wiki/Don%27t_repeat_yourself)

2022-04-08 04:13 UTC, igor-paiva commented on src/resources/metrics.py
> +        id_wanted = data["id_wanted"]
Esse nome não é muito descritivo (tanto a var quanto a chave do JSON). É o ID da pré configuração que tal nomear assim?

2022-04-09 17:45 UTC, igor-paiva requested changes

2022-04-09 17:45 UTC, igor-paiva commented on src/resources/metrics.py
> +                Metrics(metrics_list=data).save()
Como que a gente sabe de que pré configuração são essas métricas? Acho que precisamos salvar isso de alguma forma, não?

2022-04-09 17:45 UTC, igor-paiva commented on src/model/metric.py
> +    metrics_list = me.DictField()
Como que a gente sabe de que pré configuração são essas métricas? Acho que precisamos salvar isso de alguma forma, não?

2022-04-09 17:45 UTC, igor-paiva commented on src/resources/metrics.py
> +        except Exception as InvalidQueryError:
Precisa desse `Exception as InvalidQueryError`? Não sei se tá assim por algum motivo específico

2022-04-09 17:50 UTC, Rhuancpq commented on src/model/metric.py
> +    tests = me.FloatField()
basicamente é pegar a chave components e guardar tudo no banco

2022-04-09 21:48 UTC, igor-paiva requested changes

2022-04-09 21:48 UTC, igor-paiva commented on src/resources/metrics.py
> +                Metrics(metrics_list=data).save()
Não é bom dar 2 `save()` em seguida, isso força uma ida no banco de dados (que é um pouco lento). Que tal:

```py
Metrics(
  pre_config_id=data.pop("pre_config_id", None),
  metrics_list=data
).save()
```

Testei aqui e funcionou.

2022-04-09 21:48 UTC, igor-paiva commented on src/resources/metrics.py
> +        except Exception:
Tomar cuidado com isso porque nesse caso estamos tratando todas as exceções que são `Exception` ou todos os seus filhos (que são muitos).

Nesse caso é bom tratar apenas a exceção de quando o ID é inválido, pq aí podemos responder com 404. Entendem?

Outro ponto importante o método `save()` também roda as validações que tem na model (campos que são obrigatórios, validações customizadas e etc). Então ao tratar tanto a busca quanto a parte salvar nesse try a gente tá perdendo um erro importante que seria na parte de salvar. Nesse caso é melhor deixar o try/except só no if da busca, como não temos validações e nem nada para tratar no save podemos deixar de lado ou fazer outr try/except pra ele (mas no momento acho que não precisa).

Aproveitem e vejam sobre [guard clause](https://discord.com/channels/938791688556666940/942765697472266251/954774023424856124). E o porque não precisa desse else.

Referências:
- https://docs.python.org/3/library/exceptions.html#exception-hierarchy

2022-04-11 23:56 UTC, thiagolopess approved these changes

2022-04-12 00:02 UTC, igor-paiva approved these changes

2022-04-12 14:37 UTC, igor-paiva approved these changes

2022-04-12 15:58 UTC, merged